swagger: '2.0'
info:
  title: UI Accessibility Utilities
  description: RGB Color Code converts to colorname API service
  version: v1
  x-doc-swaggerUI:
  - url: 'http://poc-swagger01:8080/swagger/'
  - Explore: 'http://poc-swagger01:8080/swaggerdocs/ui-accessibility-utilities_swagger_v1.0.0a1.yaml'
  x-uri-list:
  - GET: '/color/rgb'

host: ingress.dev-c1v4.os.maeagle.corp
basePath: /ui_accessibility_utilities/v1
schemes:
- http
security:
- UserSecurity: []
paths:
  '/color/rgb':
    get:
      consumes:
      - application/json
      produces:
      - application/json
      description: 'Get the name of the color for the given RGB color code'
      tags:
      - ui_accessibility_utilities
      parameters:
      - in: header
        name: Content-Type
        description: |-
          Content type of the Request
        required: true
        type: string
      - in: header
        name: Accept
        description: |-
          Content type of the Request
        required: true
        type: string
      - in: query
        name: color
        description: |-
          rgb color code numbers for the name
        required: true
        type: string
      responses:
        '200':
          description: Successful response
          headers:
            correlation-id:
              type: string
              description: |-
                the correlation id as either passed in or generated by
                the service
          schema:
            type: object
            required:
              - color_name
              - color_rgb
              - color_hex
              - color_diff
            properties:
              color_name:
                description: name of the color
                type: string
                example: "blue"
              color_rgb:
                description: list of 3 RGB color code numbers
                type: number
                example: [222, 184, 135]
              color_hex:
                description: hexadecimal value of the color code
                type: string
                example: #DEB887
              color_diff:
                description: difference or distance between the given color code and the approximate color name
                type: string
                example: "(+1,+2,-2)"

        '400':
          $ref: '#/responses/400_error_def'
        '404':
          $ref: '#/responses/404_error_def'
        '500':
          $ref: '#/responses/500_error_def'

responses:
  400_error_def:
    description: Bad Request
    headers:
      correlation-id:
        type: string
        description: the correlation id as either passed in or generated by the service
    schema:
      description: |-
        "errors": an array of error objects containing error information
        returned on an unsuccessful call
      type: object
      required:
      - errors
      - correlation_id
      - meta
      properties:
        errors:
          type: array
          items:
            type: object
            required:
            - status
            - code
            - cause
            - message
            properties:
              status:
                description: Http status code
                type: string
                example: '400 Bad Request'
              code:
                description: Error code
                type: string
              cause:
                description: Cause of error
                type: string
              message:
                description: Error message
                type: string
        correlation_id:
          description: |-
            the correlation id as either passed in or generated by the
            service
          type: string
          example: 'da7cdff7-4cad-4ab8-8a8e-6a66072c60ee'
        meta:
          description: uv error info
          type: object
          required:
          - svrStatus
          - svrMessage
          - svrCtrlCode
          - svrCtrlName
          - svrLsDate
          - svrLsTime
          properties:
            svrStatus:
              description: uv status code
              type: integer
              example: -1
            svrMessage:
              description: uv message
              type: string
              example: 'Some error has occurred'
            svrCtrlCode:
              description: unique code (first 8 digits of correlation-id)
              type: string
              example: 'da7cdff7'
            svrCtrlName:
              description: key for content
              type: string
              example: 'errSystem'
            svrLsDate:
              description: date
              type: string
              example: '01/01/2019'
            svrLsTime:
              description: time
              type: string
              example: '12:01:01pm'
  404_error_def:
    description: Not Found
    headers:
      correlation-id:
        type: string
        description: the correlation id as either passed in or generated by the service
    schema:
      description: |-
        "errors": an array of error objects containing error information
        returned on an unsuccessful call
      type: object
      required:
      - meta
      - correlation_id
      - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
            - status
            - code
            - cause
            - message
            properties:
              status:
                description: Http status code
                type: string
                example: '404 Not Found'
              code:
                description: Error code
                type: string
              cause:
                description: Cause of error
                type: string
              message:
                description: Error message
                type: string
        correlation_id:
          description: |-
            the correlation id as either passed in or generated by the
            service
          type: string
          example: 'da7cdff7-4cad-4ab8-8a8e-6a66072c60ee'
        meta:
          description: uv error info
          type: object
          required:
          - svrStatus
          - svrMessage
          - svrCtrlCode
          - svrCtrlName
          - svrLsDate
          - svrLsTime
          properties:
            svrStatus:
              description: uv status code
              type: integer
              example: -1
            svrMessage:
              description: uv message
              type: string
              example: 'Some error has occurred'
            svrCtrlCode:
              description: unique code (first 8 digits of correlation-id)
              type: string
              example: 'da7cdff7'
            svrCtrlName:
              description: key for content
              type: string
              example: 'errSystem'
            svrLsDate:
              description: date
              type: string
              example: '01/01/2019'
            svrLsTime:
              description: time
              type: string
              example: '12:01:01pm'

  500_error_def:
    description: Internal Server Error
    headers:
      correlation-id:
        type: string
        description: the correlation id as either passed in or generated by the service
    schema:
      description: |-
        "errors": an array of error objects containing error information
        returned on an unsuccessful call
      type: object
      required:
      - errors
      - correlation_id
      - meta
      properties:
        errors:
          type: array
          items:
            type: object
            required:
            - status
            - code
            - cause
            - message
            properties:
              status:
                description: Http status code
                type: string
                example: '500 Internal Server Error'
              code:
                description: Error code
                type: string
                example: 'Unhandled Error'
              cause:
                description: Cause of error
                type: string
                example: 'An unexpected error occurred.'
              message:
                description: Error message
                type: string
                example: 'Contact PyMSA team'
        correlation_id:
          description: |-
            the correlation id as either passed in or generated by the
            service
          type: string
          example: 'da7cdff7-4cad-4ab8-8a8e-6a66072c60ee'
        meta:
          description: uv error info
          type: object
          required:
          - svrStatus
          - svrMessage
          - svrCtrlCode
          - svrCtrlName
          - svrLsDate
          - svrLsTime
          properties:
            svrStatus:
              description: uv status code
              type: integer
              example: -1
            svrMessage:
              description: uv message
              type: string
              example: 'Internal Server Error'
            svrCtrlCode:
              description: unique code (first 8 digits of correlation-id)
              type: string
              example: 'da7cdff7'
            svrCtrlName:
              description: key for content
              type: string
              example: 'errSystem'
            svrLsDate:
              description: date
              type: string
              example: '01/01/2019'
            svrLsTime:
              description: time
              type: string
              example: '12:01:01pm'

securityDefinitions:
  UserSecurity:
    type: apiKey
    name: user_key
    in: header
